### ISSUE TITLE
no read Storage example

### ISSUE THREAD

**Issue by shaokeke** [thenadz/binary-compound-file-reader#1]
please up Storage example

**Comment by thenadz** [comment]
What do you wean my storage example? If you mean writing compound files, this is a noted limitation in the readme. Right now reading the files is all that’s supported.

**Comment by shaokeke** [comment]
Now, I can only read the stream but not storage.   There are lots of levels, how can I get to the target I want.

发送自 Windows 10 版邮件应用

发件人: Dan Rossiter
发送时间: 2019年3月1日 23:57
收件人: thenadz/binary-compound-file-reader
抄送: shaokeke; Author
主题: Re: [thenadz/binary-compound-file-reader] no read Storage example(#1)

What do you wean my storage example? If you mean writing compound files, this is a noted limitation in the readme. Right now reading the files is all that’s supported.

**Comment by thenadz** [comment]
What kind of file are you trying to read? Can you provide an example?

**Comment by shaokeke** [comment]
Now ,I can get stream not storage by your phpcode
发送自 Windows 10 版邮件应用

发件人: Dan Rossiter
发送时间: 2019年3月1日 23:57
收件人: thenadz/binary-compound-file-reader
抄送: shaokeke; Author
主题: Re: [thenadz/binary-compound-file-reader] no read Storage example(#1)

What do you wean my storage example? If you mean writing compound files, this is a noted limitation in the readme. Right now reading the files is all that’s supported.

**Comment by shaokeke** [comment]
I am a php coder, first file is slidefile ,second is C# example from my friend (OpenMcdf), I do not know how to use php code to finish it,can you help me? Looking farward to yur reply!

发送自 Windows 10 版邮件应用

发件人: Dan Rossiter
发送时间: 2019年3月2日 0:14
收件人: thenadz/binary-compound-file-reader
抄送: shaokeke; Author
主题: Re: [thenadz/binary-compound-file-reader] no read Storage example(#1)

What kind of file are you trying to read? Can you provide an example?

**Comment by thenadz** [comment]
What file are you referencing? I don’t see a PHP file or a C# file.

**Comment by shaokeke** [comment]
Index.php,I am working on ,see attachment

发送自 Windows 10 版邮件应用

发件人: Dan Rossiter
发送时间: 2019年3月2日 1:53
收件人: thenadz/binary-compound-file-reader
抄送: shaokeke; Author
主题: Re: [thenadz/binary-compound-file-reader] no read Storage example(#1)

What file are you referencing? I don’t see a PHP file or a C# file.

**Comment by thenadz** [comment]
There is no attachment. You can’t attach files directly here.

**Comment by shaokeke** [comment]
I am push to https://github.com/shaokeke/mds   thank for you patient reply ,

发送自 Windows 10 版邮件应用

发件人: Dan Rossiter
发送时间: 2019年3月2日 3:48
收件人: thenadz/binary-compound-file-reader
抄送: shaokeke; Author
主题: Re: [thenadz/binary-compound-file-reader] no read Storage example(#1)

There is no attachment. You can’t attach files directly here.
